DELIMITER $$

DROP TRIGGER IF EXISTS `DesatribuirCultura` $$
CREATE DEFINER=`root`@`localhost`
TRIGGER `DesatribuirCultura` BEFORE DELETE ON `utilizador` FOR EACH ROW
BEGIN
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
        SET FOREIGN_KEY_CHECKS = 1;
    DECLARE EXIT HANDLER FOR SQLWARNING
        SET FOREIGN_KEY_CHECKS = 1;
    DECLARE EXIT HANDLER FOR NOT FOUND
        SET FOREIGN_KEY_CHECKS = 1;

    SET FOREIGN_KEY_CHECKS = 0;
    UPDATE cultura
    SET IDUtilizador = "NÃO_ATRIBUÍDA", Estado = 0
    WHERE IDUtilizador = OLD.IDUtilizador;
    SET FOREIGN_KEY_CHECKS = 1;

END$$

DELIMITER ;